### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by deanmark** [hmichaeli/alias_free_convnets#1]
When do you plan on releasing the pretrained weights for the model? Thanks

**Comment by hmichaeli** [comment]
pre-trained weights can be downloaded from: 
https://drive.google.com/drive/folders/1IsqMWL8OVKNDQ7CNaHe8F2ox7GDmwMUs?usp=share_link

**Comment by deanmark** [comment]
@hmichaeli Access to the weights is restricted 
![image](https://github.com/hmichaeli/alias_free_convnets/assets/2552482/e9e618c0-16f8-4317-9799-d5e969f53893)
