### ISSUE TITLE
what is the data preprocess?

### ISSUE THREAD

**Issue by ofirshifman** [hmichaeli/alias_free_convnets#3]
Hi, I'm trying to use you pretrained model from huggingface, and wanted to know how should I use it to infer a new image.
I want to make sure I'm using it the same way you did in training.

can you please add inferance example to the huggingface demo?

Thanks!
Ofir (from HUJI)

**Comment by hmichaeli** [comment]
Hi,
The training regime is the same as in the original ConvNeXt paper. You can look for more details there, or follow the training script in our implementation.
I added a short evaluation script in huggingface for ease.
